# Generated by Django 3.1.3 on 2021-02-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copouns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='copounassignment',
            name='code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
